# Generated by Django 5.2.14 on 2026-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_auditoria_descripcion_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
